// Code generated by "stringer -type DownloadStatus src/telegram_youtube_bot/lib/Request.go"; DO NOT EDIT.

package telegram_youtube_bot

import "fmt"

const _DownloadStatus_name = "WaitingForDownloadDownloadingDownloadDoneFailedStoppedWaitingForUploadUploadingUploadDone"

var _DownloadStatus_index = [...]uint8{0, 18, 29, 41, 47, 54, 70, 79, 89}

func (i DownloadStatus) String() string {
	if i < 0 || i >= DownloadStatus(len(_DownloadStatus_index)-1) {
		return fmt.Sprintf("DownloadStatus(%d)", i)
	}
	return _DownloadStatus_name[_DownloadStatus_index[i]:_DownloadStatus_index[i+1]]
}
